[tool.poetry]
name = "tabular_compettion_template"
version = "0.1.0"
description = ""
authors = ["yumizu"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10.0,<=3.10.12"
hydra-core = "^1.3.2"
omegaconf = "^2.3.0"
numpy = "^1.25.2"
pandas = "^2.1.3"
category-encoders = "^2.6.3"
ipykernel = "^6.27.1"
wandb = "^0.16.0"
lightgbm = "^4.1.0"
matplotlib = "^3.8.2"
seaborn = "^0.12.0"
matplotlib-venn = "^0.11.9"
japanize-matplotlib = "^1.1.3"
scikit-learn = "^1.3.2"
catboost = "^1.2.2"
ydata-profiling = "^4.6.3"
ipywidgets = "^8.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pyproject-flake8 = "^6.0.0.post1"
black = "^22.12.0"
mypy = "^0.991"
isort = "^5.11.4"
pytest = "^7.2.0"
mdformat-gfm = "^0.3.5"
mdformat-frontmatter = "^2.0.1"
mdformat_footnote = "^0.1.1"

[tool.flake8]
max-line-length = 119

[tool.black]
line-length = 119

[tool.isort]
line_length = 119
profile = "black"

[tool.mypy]
ignore_missing_imports = true
