defaults:
  - _self_
  - setting: base
  - dir: base
  - model: lightgbm
  - override hydra/job_logging: none # hydraで自動的にログファイルが生成されるのを防ぐ

hydra:
  # hydraで自動的にログファイルが生成されるのを防ぐ
  output_subdir: null
  job:
    chdir: False
  run:
    dir: .
